"use client";

import React, { createContext, useContext, useEffect, useState } from 'react';

type Theme = 'light' | 'dark';
type Language = 'en' | 'ar';

interface AppContextType {
  theme: Theme;
  toggleTheme: () => void;
  language: Language;
  toggleLanguage: () => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Navbar
    appName: "RAGify",
    getStarted: "Launch App",
    navFeatures: "Features",
    navHow: "How it works",
    // Hero
    heroTag: "AI-Powered Document Intelligence",
    subtitle: "The Smartest Document & Data Analysis System",
    titleLine1: "Understand Your Data",
    titleLine2: "Like Never Before",
    description: "Upload your PDFs or Excel files, and let AI read, analyze, and extract precise details and interactive dashboards in seconds.",
    tryForFree: "Try For Free — It's Free",
    learnMore: "Learn More",
    // Stats
    statLocal: "Local & Private",
    statModels: "AI Models",
    statFiles: "File Support",
    // How it works
    howTitle: "How RAGify Works",
    howSubtitle: "Three simple steps to unlock the power of your documents.",
    step1Title: "Upload Your File",
    step1Desc: "Drop any PDF or Excel file. RAGify securely processes it on your local backend.",
    step2Title: "AI Processes It",
    step2Desc: "The system chunks, embeds, and stores your data locally using FAISS for lightning-fast retrieval.",
    step3Title: "Ask & Analyze",
    step3Desc: "Chat with your documents or view auto-generated analytics dashboards from your Excel data.",
    // Features
    featuresTitle: "Everything You Need",
    featuresSubtitle: "A complete AI document intelligence platform, running 100% on your machine.",
    feature1Title: "Limitless Reading",
    feature1Desc: "Upload any file size. The system has a permanent memory to analyze and retrieve every character.",
    feature2Title: "Data Analytics",
    feature2Desc: "Upload Excel files and we will generate professional, interactive, and downloadable dashboards instantly.",
    feature3Title: "Zero Downtime",
    feature3Desc: "Auto-fallback system between top models ensures 24/7 free uptime.",
    feature4Title: "Conversational AI",
    feature4Desc: "Ask natural language questions about your documents and receive accurate, context-aware answers.",
    feature5Title: "100% Local & Private",
    feature5Desc: "Your data never leaves your machine. FAISS runs locally with no cloud dependency.",
    feature6Title: "Multi-Language",
    feature6Desc: "Full Arabic and English support with dynamic RTL layout switching.",
    // CTA
    ctaTitle: "Ready to Analyze Your Data?",
    ctaSubtitle: "Join the future of document intelligence. No sign-up. No credit card. Just upload and ask.",
    ctaBenefit1: "No sign-up required",
    ctaBenefit2: "100% Local & Private",
    ctaBenefit3: "Free Forever",
    // Footer
    footerText: "© 2025 RAGify. Built with Next.js & FastAPI.",
    // Dashboard
    uploadFiles: "Upload Files",
    clickToSelect: "Click to select a file",
    supportsFormats: "Supports PDF, DOCX, PPTX, TXT, Excel, Images",
    processFile: "Process File",
    processing: "Processing...",
    uploading: "Uploading...",
    viewAnalytics: "View Analytics Dashboard",
    aiAssistant: "AI Assistant (RAG)",
    askAnything: "Ask me anything about your files...",
    localtunnelUrl: "Backend URL (optional)",
    leaveEmpty: "Leave empty to use default local server (localhost:9999).",
    noFilesYet: "No files indexed yet",
    clearChat: "Clear chat",
    filesIndexed: "file(s) indexed",
    dropFileOrClick: "Drop file or click to select",
    selectMultiple: "You can select multiple files",
    removeFile: "Remove file",
    uploadAll: "Upload All Files",
    // API Key
    generateApiKey: "Generate API Key",
    apiKeyTitle: "Developer API Key",
    apiKeyDesc: "Share this key with developers to integrate RAGify into their own projects.",
    generateKey: "Generate New Key",
    copyKey: "Copy Key",
    copied: "Copied!",
    apiKeyUsage: 'Use this key in the X-Api-Key header for all API requests.',
    // Reset
    resetMemory: "Reset Knowledge Base",
    // Analytics
    analyticsDashboard: "Analytics Dashboard",
    downloadReport: "Download Report",
    totalRows: "Total Rows",
    totalColumns: "Total Columns",
    aiInsights: "AI Insights",
    detectedColumns: "Detected Columns",
    autoGeneratedChart: "Auto-Generated Chart",
    noData: "No analysis data found. Please upload an Excel file first.",
    returnDashboard: "Return to Dashboard",
  },
  ar: {
    // Navbar
    appName: "RAGify",
    getStarted: "افتح التطبيق",
    navFeatures: "المميزات",
    navHow: "كيف يعمل",
    // Hero
    heroTag: "ذكاء اصطناعي لتحليل المستندات",
    subtitle: "أذكى نظام لتحليل المستندات والبيانات",
    titleLine1: "افهم بياناتك",
    titleLine2: "كما لم تفعل من قبل",
    description: "ارفع ملفات الـ PDF أو الـ Excel الخاصة بك، ودع الذكاء الاصطناعي يقرأ، يحلل، ويستخرج تفاصيل دقيقة ولوحات معلومات تفاعلية في ثوانٍ.",
    tryForFree: "جرب مجاناً — بدون تسجيل",
    learnMore: "اعرف أكثر",
    // Stats
    statLocal: "محلي وخاص",
    statModels: "نماذج ذكاء اصطناعي",
    statFiles: "دعم الملفات",
    // How it works
    howTitle: "كيف يعمل RAGify",
    howSubtitle: "ثلاث خطوات بسيطة لاستخراج قوة مستنداتك.",
    step1Title: "ارفع ملفك",
    step1Desc: "أضف أي ملف PDF أو Excel. يعالجه RAGify بأمان على السيرفر المحلي الخاص بك.",
    step2Title: "الذكاء الاصطناعي يعالجه",
    step2Desc: "يقوم النظام بتقطيع البيانات وتضمينها وتخزينها محلياً باستخدام FAISS للاسترجاع الفوري.",
    step3Title: "اسأل وحلل",
    step3Desc: "تحدث مع مستنداتك أو اعرض لوحات التحليل التلقائية من بيانات Excel.",
    // Features
    featuresTitle: "كل ما تحتاجه",
    featuresSubtitle: "منصة ذكاء اصطناعي متكاملة لتحليل المستندات، تعمل 100% على جهازك.",
    feature1Title: "قراءة بلا حدود",
    feature1Desc: "ارفع أي حجم ملف. النظام يمتلك ذاكرة دائمة لتحليل واسترجاع كل حرف.",
    feature2Title: "تحليل البيانات",
    feature2Desc: "ارفع ملفات Excel وسنقوم بإنشاء لوحات معلومات احترافية وتفاعلية وقابلة للتحميل فوراً.",
    feature3Title: "تشغيل دائم",
    feature3Desc: "نظام التبديل التلقائي بين أفضل النماذج يضمن لك تشغيلاً مجانياً على مدار الساعة.",
    feature4Title: "محادثة ذكية",
    feature4Desc: "اطرح أسئلة بلغة طبيعية عن مستنداتك واحصل على إجابات دقيقة ومدركة للسياق.",
    feature5Title: "100% خاص ومحلي",
    feature5Desc: "بياناتك لا تغادر جهازك أبداً. FAISS يعمل محلياً بدون أي اعتماد على السحابة.",
    feature6Title: "متعدد اللغات",
    feature6Desc: "دعم كامل للعربية والإنجليزية مع تبديل ديناميكي لتخطيط RTL.",
    // CTA
    ctaTitle: "مستعد لتحليل بياناتك؟",
    ctaSubtitle: "انضم لمستقبل ذكاء المستندات. بدون تسجيل. بدون بطاقة ائتمان. فقط ارفع واسأل.",
    ctaBenefit1: "بدون تسجيل",
    ctaBenefit2: "خاص ومحلي 100%",
    ctaBenefit3: "مجاني للأبد",
    // Footer
    footerText: "© 2025 RAGify. مبني بـ Next.js و FastAPI.",
    // Dashboard
    uploadFiles: "رفع الملفات",
    clickToSelect: "انقر لاختيار ملف",
    supportsFormats: "يدعم PDF, DOCX, PPTX, TXT, Excel, الصور",
    processFile: "معالجة الملف",
    processing: "جاري المعالجة...",
    uploading: "جاري الرفع...",
    viewAnalytics: "عرض لوحة التحليلات",
    aiAssistant: "المساعد الذكي (RAG)",
    askAnything: "اسألني أي شيء عن ملفاتك...",
    localtunnelUrl: "رابط الـ Backend (اختياري)",
    leaveEmpty: "اتركه فارغاً لاستخدام السيرفر المحلي (localhost:9999).",
    noFilesYet: "لا توجد ملفات بعد",
    clearChat: "مسح المحادثة",
    filesIndexed: "ملف مفهرس",
    dropFileOrClick: "اسحب الملف أو انقر للاختيار",
    selectMultiple: "يمكنك اختيار ملفات متعددة",
    removeFile: "إزالة الملف",
    uploadAll: "رفع جميع الملفات",
    // API Key
    generateApiKey: "توليد مفتاح API",
    apiKeyTitle: "مفتاح API للمطورين",
    apiKeyDesc: "شارك هذا المفتاح مع المطورين لدمج RAGify في مشاريعهم الخاصة.",
    generateKey: "توليد مفتاح جديد",
    copyKey: "نسخ المفتاح",
    copied: "تم النسخ!",
    apiKeyUsage: "استخدم هذا المفتاح في header الـ X-Api-Key مع كل طلب API.",
    // Reset
    resetMemory: "مسح قاعدة المعرفة",
    // Analytics
    analyticsDashboard: "لوحة التحليلات",
    downloadReport: "تحميل التقرير",
    totalRows: "إجمالي الصفوف",
    totalColumns: "إجمالي الأعمدة",
    aiInsights: "رؤى الذكاء الاصطناعي",
    detectedColumns: "الأعمدة المكتشفة",
    autoGeneratedChart: "رسم بياني تلقائي",
    noData: "لا توجد بيانات تحليل. يرجى رفع ملف Excel أولاً.",
    returnDashboard: "العودة إلى لوحة التحكم",
  }
};

const AppContext = createContext<AppContextType | undefined>(undefined);

export function AppProvider({ children }: { children: React.ReactNode }) {
  const [theme, setTheme] = useState<Theme>('dark');
  const [language, setLanguage] = useState<Language>('en');

  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    // eslint-disable-next-line
    setMounted(true);
    const savedTheme = localStorage.getItem('theme') as Theme | null;
    if (savedTheme) {
      setTheme(savedTheme);
    } else if (window.matchMedia('(prefers-color-scheme: light)').matches) {
      setTheme('light');
    }

    const savedLang = localStorage.getItem('language') as Language | null;
    if (savedLang) {
      setLanguage(savedLang);
    }
  }, []);

  useEffect(() => {
    if (!mounted) return;
    localStorage.setItem('theme', theme);
    if (theme === 'dark') {
      document.documentElement.classList.add('dark');
    } else {
      document.documentElement.classList.remove('dark');
    }
  }, [theme, mounted]);

  useEffect(() => {
    if (!mounted) return;
    localStorage.setItem('language', language);
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language, mounted]);

  const toggleTheme = () => {
    setTheme(prev => prev === 'dark' ? 'light' : 'dark');
  };

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'en' ? 'ar' : 'en');
  };

  const t = (key: string): string => {
    return (translations[language] as Record<string, string>)[key] || key;
  };

  return (
    <AppContext.Provider value={{ theme, toggleTheme, language, toggleLanguage, t }}>
      {children}
    </AppContext.Provider>
  );
}

export function useAppContext() {
  const context = useContext(AppContext);
  if (!context) {
    // Return a safe fallback object during prerendering if context is undefined
    return {
      theme: 'dark' as Theme,
      toggleTheme: () => {},
      language: 'en' as Language,
      toggleLanguage: () => {},
      t: (key: string) => key
    };
  }
  return context;
}
