"use client";

import React, { createContext, useContext, useEffect, useState } from 'react';

type Theme = 'light' | 'dark';
type Language = 'en' | 'ar';

interface AppContextType {
  theme: Theme;
  toggleTheme: () => void;
  language: Language;
  toggleLanguage: () => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Navbar
    appName: "RAGify",
    getStarted: "Get Started",
    // Landing Page
    subtitle: "The Smartest Document & Data Analysis System",
    titleLine1: "Understand Your Data",
    titleLine2: "Like Never Before",
    description: "Upload your PDFs or Excel files, and let AI read, analyze, and extract precise details and interactive dashboards in seconds.",
    tryForFree: "Try For Free",
    feature1Title: "Limitless Reading",
    feature1Desc: "Upload any file size. The system has a permanent memory to analyze and retrieve every character.",
    feature2Title: "Data Analysis",
    feature2Desc: "Upload Excel files and we will generate professional, interactive, and downloadable dashboards instantly.",
    feature3Title: "Zero Downtime",
    feature3Desc: "Auto-fallback system between top models ensures 24/7 free uptime.",
    // Dashboard
    uploadFiles: "Upload Files",
    clickToSelect: "Click to select a file",
    supportsFormats: "Supports PDF, Excel (.xlsx, .xls)",
    processFile: "Process File",
    processing: "Processing...",
    viewAnalytics: "View Analytics Dashboard",
    aiAssistant: "AI Assistant (RAG)",
    askAnything: "Ask me anything about your files...",
    localtunnelUrl: "Localtunnel Backend URL",
    leaveEmpty: "Leave empty to use default local server (localhost:9999).",
    // Analytics
    analyticsDashboard: "Analytics Dashboard",
    downloadReport: "Download Report",
    totalRows: "Total Rows",
    totalColumns: "Total Columns",
    aiInsights: "AI Insights",
    detectedColumns: "Detected Columns",
    autoGeneratedChart: "Auto-Generated Chart",
    noData: "No analysis data found. Please upload an Excel file first.",
    returnDashboard: "Return to Dashboard",
  },
  ar: {
    // Navbar
    appName: "RAGify",
    getStarted: "ابدأ الآن",
    // Landing Page
    subtitle: "أذكى نظام لتحليل المستندات والبيانات",
    titleLine1: "افهم بياناتك",
    titleLine2: "كما لم تفعل من قبل",
    description: "ارفع ملفات الـ PDF أو الـ Excel الخاصة بك، ودع الذكاء الاصطناعي يقرأ، يحلل، ويستخرج تفاصيل دقيقة ولوحات معلومات تفاعلية في ثوانٍ.",
    tryForFree: "جرب مجاناً",
    feature1Title: "قراءة بلا حدود",
    feature1Desc: "ارفع أي حجم ملف. النظام يمتلك ذاكرة دائمة لتحليل واسترجاع كل حرف.",
    feature2Title: "تحليل البيانات",
    feature2Desc: "ارفع ملفات Excel وسنقوم بإنشاء لوحات معلومات احترافية وتفاعلية وقابلة للتحميل فوراً.",
    feature3Title: "تشغيل دائم",
    feature3Desc: "نظام التبديل التلقائي بين أفضل النماذج يضمن لك تشغيلاً مجانياً على مدار الساعة.",
    // Dashboard
    uploadFiles: "رفع الملفات",
    clickToSelect: "انقر لاختيار ملف",
    supportsFormats: "يدعم PDF, Excel (.xlsx, .xls)",
    processFile: "معالجة الملف",
    processing: "جاري المعالجة...",
    viewAnalytics: "عرض لوحة التحليلات",
    aiAssistant: "المساعد الذكي (RAG)",
    askAnything: "اسألني أي شيء عن ملفاتك...",
    localtunnelUrl: "رابط سيرفر Localtunnel",
    leaveEmpty: "اتركه فارغاً لاستخدام السيرفر المحلي (localhost:9999).",
    // Analytics
    analyticsDashboard: "لوحة التحليلات",
    downloadReport: "تحميل التقرير",
    totalRows: "إجمالي الصفوف",
    totalColumns: "إجمالي الأعمدة",
    aiInsights: "رؤى الذكاء الاصطناعي",
    detectedColumns: "الأعمدة المكتشفة",
    autoGeneratedChart: "رسم بياني تلقائي",
    noData: "لا توجد بيانات تحليل. يرجى رفع ملف Excel أولاً.",
    returnDashboard: "العودة إلى لوحة التحكم",
  }
};

const AppContext = createContext<AppContextType | undefined>(undefined);

export function AppProvider({ children }: { children: React.ReactNode }) {
  const [theme, setTheme] = useState<Theme>('dark');
  const [language, setLanguage] = useState<Language>('en');

  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    // eslint-disable-next-line
    setMounted(true);
    const savedTheme = localStorage.getItem('theme') as Theme | null;
    if (savedTheme) {
      setTheme(savedTheme);
    } else if (window.matchMedia('(prefers-color-scheme: light)').matches) {
      setTheme('light');
    }

    const savedLang = localStorage.getItem('language') as Language | null;
    if (savedLang) {
      setLanguage(savedLang);
    }
  }, []);

  useEffect(() => {
    if (!mounted) return;
    localStorage.setItem('theme', theme);
    if (theme === 'dark') {
      document.documentElement.classList.add('dark');
    } else {
      document.documentElement.classList.remove('dark');
    }
  }, [theme, mounted]);

  useEffect(() => {
    if (!mounted) return;
    localStorage.setItem('language', language);
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language, mounted]);

  const toggleTheme = () => {
    setTheme(prev => prev === 'dark' ? 'light' : 'dark');
  };

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'en' ? 'ar' : 'en');
  };

  const t = (key: string): string => {
    return (translations[language] as Record<string, string>)[key] || key;
  };

  return (
    <AppContext.Provider value={{ theme, toggleTheme, language, toggleLanguage, t }}>
      {children}
    </AppContext.Provider>
  );
}

export function useAppContext() {
  const context = useContext(AppContext);
  if (!context) {
    throw new Error('useAppContext must be used within an AppProvider');
  }
  return context;
}
